# I.1. Un scalaire

In [ ]:
# https://www.youtube.com/watch?v=GdWuZkgOOQc  
# from foxx py en français

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
scalaire = np.array(3)
scalaire

array(3)

In [4]:
type(scalaire)

numpy.ndarray

# I.2. Un tableau à 1 dimension

In [5]:
vecteur = np.array([1,2,3])
vecteur

array([1, 2, 3])

In [6]:
type(vecteur)

numpy.ndarray

In [7]:
type([1,2,3])

list

# I.3. Un tableau à 2 dimensions

In [8]:
matrice = np.array([[1,2,3], [4,5,6]])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(matrice)

numpy.ndarray

In [10]:
type([[1,2,3], [4,5,6]])

list

# I.4. Utiliser print() avec nd.array

In [11]:
print(scalaire)

3


In [12]:
print(vecteur)

[1 2 3]


In [13]:
print(matrice)

[[1 2 3]
 [4 5 6]]


# I.5. Connaître les dimensions d'un array

In [15]:
scalaire.shape

()

In [16]:
vecteur.shape

(3,)

In [17]:
matrice.shape

(2, 3)

In [18]:
matrice1 = np.array([[1,2],[3,4], [5,6], [5,6]])

In [19]:
matrice1

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6]])

In [20]:
matrice1.shape


(4, 2)

In [23]:
matrice2 = np.array([[1,2,3,4,5], [6,7,8, 9,10]])
matrice2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
matrice2.shape

(2, 5)

### L'attribut shape

In [27]:
matrice2.shape[0]

2

In [28]:
matrice2.shape[1]

5

### Un vecteur avec une seule valeur

In [43]:
scalaire1 = np.array(0)
nombre_dimension_1 = np.array([0])
print(scalaire1.shape)
print(nombre_dimension_1.shape)

()
(1,)


# I.6. Les différences entre list et un objet narray

### I.6.1. La méthode len() et l'attribut shape

In [44]:
liste = [1,2,3,4,5]
len(liste)

5

In [45]:
liste0 = [[1,2,3],[4,5,6]]
len(liste0)

2

### I.6.2. L'opérateur somme: +

In [47]:
liste_1= [1,2,3]
liste_2= [4,5,6]
liste_1 + liste_2

[1, 2, 3, 4, 5, 6]

In [49]:
scalaire_1 = np.array(2)
scalaire_2 = np.array(3)
scalaire_1 + scalaire_2

5

In [56]:
vecteur_1 = np.array([11,2,3])
vecteur_2 = np.array([-1,-2,-3])
somme_vecteur = vecteur_1 + vecteur_2
somme_vecteur
print(somme_vecteur)
print(vecteur_1, "+", vecteur_2, "=", somme_vecteur)

[10  0  0]
[11  2  3] + [-1 -2 -3] = [10  0  0]


In [61]:
matrice_1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrice_2 = np.array([[4,5,6], [7,8,9], [1,2,3]])
somme_matrice = matrice_1 + matrice_2
somme_matrice

array([[ 5,  7,  9],
       [11, 13, 15],
       [ 8, 10, 12]])

In [63]:
print(matrice_1)
print("     +")
print(matrice_2)
print("      =")
print(somme_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
     +
[[4 5 6]
 [7 8 9]
 [1 2 3]]
      =
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


### I. 6.3. Les fonctions mathématiques

In [67]:
from mah import log
liste = [1,2,3,4]
log(liste) "--> donne une erreur"

SyntaxError: invalid syntax (Temp/ipykernel_1244/2994543262.py, line 3)

In [66]:
vecteur = np.array([1,2,3,4])
np.log(vecteur)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [71]:
matrice = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.sqrt(matrice)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### I.6.4 La Longueur

In [72]:
liste_de_listes = [[1,2], [1,2,3], [1,2,3,4,5]]
liste_de_listes


[[1, 2], [1, 2, 3], [1, 2, 3, 4, 5]]

In [73]:
matrice_erreur = np.array([[1,2], [1,2,3], [1,2,3,4,5]])
matrice_erreur

C:\Users\Philippe\AppData\Local\Temp/ipykernel_1244/2935809782.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matrice_erreur = np.array([[1,2], [1,2,3], [1,2,3,4,5]])


array([list([1, 2]), list([1, 2, 3]), list([1, 2, 3, 4, 5])], dtype=object)