# I.1. Exercice 1

In [2]:
import numpy as np

In [7]:
scalaire_1 = np.array(5)
scalaire_2 = np.array(6)
scalaire_1 + scalaire_2


11

In [5]:
print(scalaire_1 + scalaire_2)

11


# I.2. Exercice 2

In [8]:
vecteur_1 = np.array([1,2,3])
vecteur_2 = np.array([3,2,1])
vecteur_3 = np.array([0,1,-1])
resultat = vecteur_1 + vecteur_2 + vecteur_3
resultat

array([4, 5, 3])

In [9]:
print(resultat)

[4 5 3]


In [10]:
print(resultat.shape)

(3,)


### autre méthode

In [16]:
vecteur_1, vecteur_2, vecteur_3 = np.array([1,2,3]), np.array([3,2,1]), np.array([0,1,-1])
print(vecteur_1 + vecteur_2 + vecteur_3)
print(resultat)
resultat

[4 5 3]
[4 5 3]


array([4, 5, 3])

In [15]:
print(resultat.shape)

(3,)


# I.3. Exercice 3

In [21]:
scalaire = np.array(0)
vecteur = np.array([125,2185,321,665,17,-8])
produit = scalaire*vecteur
produit


array([0, 0, 0, 0, 0, 0])

In [22]:
print(produit)

[0 0 0 0 0 0]


# I.4. Exercice 4

In [23]:
m = np.array([[1,2,3],[4,5,6]])
m.shape

(2, 3)

# I.5. Exercice 5

In [29]:
m1 = np.array([[1,2], [3,4], [5,6],[7,8]])
m2 = np.array([[1,2], [3,4], [5,6],[7,8]])
total = m1+m2


In [30]:
total

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [34]:
total[1]

array([6, 8])

# I.6. Exercice 6

In [35]:
v1 = np.array([4, 7])
v2 = np.array([3, 6])

a1 = np.array(2)
a2 = np.array(3)
a3 = np.array(1.5)


In [36]:
v1 * a1

array([ 8, 14])

In [38]:
v2 * a2

array([ 9, 18])